name: Core

#Ejecutar solo en push
on: [push]

env:
  #Version PHP
  php: 7.4

jobs:


  PHPUnit-Docker:
    #Ejecutar pruebas 
    runs-on: ${{ matrix.os }}
    environment: Docker #Enviroment para acceder a Secrets de Docker

    services:
      exttests:
        #Imagen de Moodle para test
        image: moodlehq/moodle-exttests
        ports:
          - 8080:80
      redis:
        image: redis
        ports:
          - 6379:6379
    strategy:
      #No cancelar en caso de que falle un elemento de la matriz
      fail-fast: false
      matrix:
        include:
          #Matriz OS-PHP-DB
          - os: ubuntu-18.04
            php: 7.4
            db: pgsql

    steps:


        
      - name: Crear contenedor
        env: 
          #GitHub Secrets
          username: ${{ secrets.AZURE_USERNAME }}
          pass: ${{ secrets.AZURE_PASS }}
          dbhost: ${{ secrets.DBHOST }}

        run: |

          #Borramos el config.php de prueba
          #rm config.php
          
          #creamos el config.php de produccion
          
          echo 'unset($CFG);' > config.php
          echo 'global $CFG;' >> config.php
          echo '$CFG = new stdClass();' >> config.php
          echo '$CFG->dbtype    = "pgsql";' >> config.php
          echo '$CFG->dblibrary = "native";' >> config.php
          echo '$CFG->dbhost    = "${{ secrets.DBHOST }}";' >> config.php
          echo '$CFG->dbname = "moodle";' >> config.php
          echo '$CFG->dbuser   = "${{ secrets.DBUSER }}";' >> config.php
          echo '$CFG->dbpass   = "${{ secrets.DBPASS }}";' >> config.php
          echo '$CFG->dbprefix = "mdl_";' >> config.php
          echo '$CFG->dboptions = array ("dbpersist" => 0,"dbport" => 5432, "dbsocket" => "",);' >> config.php
          echo '$CFG->wwwroot   = "http://trabajofindegradoalbertonc.northeurope.azurecontainer.io/moodle";' >> config.php
          echo '$CFG->dirroot   = "/var/www/html/moodle";'>> config.php
          echo '$CFG->dataroot  = "/var/www/moodledata";'>> config.php
          echo '$CFG->admin     = "admin";'>> config.php
          echo '$CFG->directorypermissions = 0777;'>> config.php
          echo 'require_once(__DIR__ . "/lib/setup.php");'>> config.php

          cat config.php  
          
          #Construccion de la imagen y despliegue en ACI
          echo  ${{ secrets.AZURE_PASS }} > pass
          $ cat pass | docker login --username  ${{ secrets.AZURE_USERNAME }}  --password-stdin
          
          
          #docker login trabajofindegradoalbertonovillo.azurecr.io -p $env.pass -u $env.username
          #echo ${{ secrets.AZURE_PASS }} | docker login --username  ${{ secrets.AZURE_USERNAME }} --password-stdin
          #docker login trabajofindegradoalbertonovillo.azurecr.io --password-stdin env.pass -u env.username 
          #docker build  -t trabajofindegradoalbertonovillo.azurecr.io/moodle-tfg:1.0 . 
          #docker push trabajofindegradoalbertonovillo.azurecr.io/moodle-tfg:1.0 
          
          
  
