

on: [push, pull_request]

jobs:


    
    services:
      #servicio base de datos para la ejecucion de pruebas
      postgres:
        image: postgres:10
        
        env:
          #usuario de la base de datos
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false
      #contruccion de la matriz
      #para cada opcion de cada linea, se combina con una opcion del resto de filas.
      matrix:
        include:
          - os: ubuntu-18.04
            php: 7.4
            db: pgsql

    steps:

      #instalacion de la version de PHP correspondiente
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: max_input_vars=5000
          coverage: none
      
      #instalacion de PostgresSQL
 
      - if: ${{ matrix.db == 'pgsql' }}
        uses: m4nu56/postgresql-action@v1
        with:
          postgresql version: 9.6
          postgresql db: testdb
          postgresql user: test
          postgresql password: test

      #instalacion de PhpUnit
      - name: Setting up PHPUnit
        env:
          dbtype: ${{ matrix.db }}
        run: |
          echo "pathtophp=$(which php)" >> $GITHUB_ENV # Inject installed pathtophp to env. The template config needs it.
          cp .github/workflows/config-template.php config.php
          mkdir ../moodledata
          sudo locale-gen en_AU.UTF-8
          php admin/tool/phpunit/cli/init.php --no-composer-self-update
      
      
      #uso del script de la base de datos 
      - name: Setting up PHPUnit
        env:
          dbtype: ${{ matrix.db }}
        run:  psql -U postgres -d testdb -a -f scriptSQLTravis.sql;



      #ejecucion de pruebas unitarias
      - name: Running PHPUnit tests
        env:
          dbtype: ${{ matrix.db }}
        run: vendor/bin/phpunit -v
