name: Core

on: [push]

env:
  php: 7.4

jobs:


  PHPUnit:
    runs-on: ${{ matrix.os }}
    environment: Docker
    services:
      exttests:
        image: moodlehq/moodle-exttests
        ports:
          - 8080:80
      redis:
        image: redis
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            php: 7.4
            db: pgsql

    steps:
      - name: Crear contenedor
        if:  ${{ secrets.AZURE_USERNAME }} == 'trabajofindegradoalbertonovillo'
        run: echo "I know what the secret token is!"
