name: Core

on: [push]

env:
  php: 7.4

jobs:


  PHPUnit:
    runs-on: ${{ matrix.os }}
    services:
      exttests:
        image: moodlehq/moodle-exttests
        ports:
          - 8080:80
      redis:
        image: redis
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            php: 7.4
            db: pgsql

    steps:

      - name: Setting up DB pgsql
        if: ${{ matrix.db == 'pgsql' }}
        uses: m4nu56/postgresql-action@v1
        with:
          postgresql version: 9.6
          postgresql db: test
          postgresql user: test
          postgresql password: test

      - name: Configuring git vars
        uses: rlespinasse/github-slug-action@v3.x

      - name: Running PHPUnit tests
        run: |
          echo ${{ secrets.AZURE_USERNAME }}
          docker login trabajofindegradoalbertonovillo.azurecr.io -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASS }}
          docker build  -t trabajofindegradoalbertonovillo.azurecr.io/moodle-tfg:1.0 .
          docker push trabajofindegradoalbertonovillo.azurecr.io/moodle-tfg:1.0 
